# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cmdb_app', '0002_execl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execl',
            options={'verbose_name_plural': '托管管理表'},
        ),
        migrations.AlterField(
            model_name='execl',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
    ]
