# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cmdb_app', '0003_auto_20180102_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execl',
            name='management_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP'),
        ),
    ]
