# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cmdb_app', '0004_auto_20180103_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execl',
            name='intranet_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='execl',
            name='vlan_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='VlanIP'),
        ),
    ]
